/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
plugins {
    java
    id("io.moderne.rewrite") version ("0.24.0")
    `maven-publish`
}

group = "org.example"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

publishing {
    repositories {
        maven {
            url = uri("https://artifactory.moderne.ninja/artifactory/greg-local/")
            credentials {
                username = properties["artifactory.username"].toString()
                password = properties["artifactory.password"].toString()
            }
        }
    }
    publications {
        create<MavenPublication>("moderne") {
            artifact(tasks.named("moderneJar"))
        }
    }
}
